### PR TITLE
Move from r22 to r27

### PR DESCRIPTION
**Pull request by slaff**
https://android.googlesource.com/platform/build/+/refs/tags/android-12.1.0_r27

### CODE REVIEW

**Comment by NotNoelChannel** [comment]
did u try compiling a rom with r27? i'll merge it **### only if it works and it doesn't break the manifest**.

**Comment by slaff** [comment]
@NotNoelChannel Understood. Please, don't merge it yet. I will try to setup my Android dev environment and see if it compiles.

**Comment by NotNoelChannel** [comment]
okay, thanks

**Comment by slaff** [comment]
After a week and a bit of compilation experiments I think it will be too difficult for a single person to move from r22 to r27 before LineageOS does the move. I will close this pull request for now and eventually reopen it once the LineageOS team has moved to r27.

**Pull request closed without merging**
